from  alpine 
maintainer ashutoshh
#cmd  ping  fb.com 
#  cmd based parent process can be replaced 
entrypoint  ["ping"]
cmd  ["fb.com"] 
#  can't be replaced as argument of image during container creation time 
